spring:
  datasource:
    url: "jdbc:h2:mem:my_db"
    driverClassName: "org.h2.Driver"
    username: "admin"
    password: "test"
  jpa:
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.H2Dialect"  # Specifying the SQL dialect makes Hibernate generate better SQL for the chosen database
        ddl-auto: "update"
        jdbc:
          lob:
            non_contextual_creation: true	  # fixes Hibernate issue: https://github.com/spring-projects/spring-boot/issues/12007

